### ISSUE TITLE
Versions disappeared on conda-forge

### ISSUE THREAD

**Issue by mrava87** [conda-forge/pylops-feedstock#32]
### Comment:

Hi @jan-janssen,
I just realized that all versions but 2.1.0 and 1.8.0 have disappeared (see https://anaconda.org/conda-forge/pylops/labels). 

Do you know why this happened and if we can restore it?

**Comment by jan-janssen** [comment]
@mrava87 I am confused, for me they are still listed under https://anaconda.org/conda-forge/pylops/files?page=2

**Comment by mrava87** [comment]
Interesting, I see them too :) one of my students was trying to install pylops 1.18.3 in conda-forge and was getting an error (version not found). Let me try to trouble shoot.

Thank for the quick reply!

**Comment by jan-janssen** [comment]
@mrava87 It could depend on your students hardware, for example if they have an Apple ARM Mac and try to build an all ARM conda environment than this fails, because we only added Apple ARM support for 2.1.0

**Comment by mrava87** [comment]
Indeed, I see :)
